### ISSUE TITLE
TypeError: Expected parameter accessToken

### ISSUE THREAD

**Issue by ThomasTusche** [RJPearson94/terraform-aws-open-next#14]
## Technical Details

- Using the "tf-aws-open-next-zone" module.
- Using REGIONAL_LAMBDAs.
- Using pretty much the default settings for all the lambdas.

## Describe the bug

When trying to access the website by using the Cloudfront URL I receive an "Internal Server Error 500".
Upon checking the logs in Cloudwatch I saw an error with the server function which says:

ERROR	TypeError: Expected parameter accessToken

Unfortunately, I am no developer and have trouble understanding why it needs the accessToken and where it tries to get it from. I couldn't find any mention regarding an accessToken in your repository and I don't see the lambda function expecting it to be passed on via the environment variables

## Logs

`2024-01-02T14:44:55.684Z	6385e105-35a7-4c57-95d5-0d0005b62c43	ERROR	TypeError: Expected parameter accessToken
    at In (/var/task/node_modules/contentful/dist/contentful.node.min.js:2:243897)
    at 5746 (/var/task/.next/server/pages/[[...slug]].js:2085:68)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at /var/task/.next/server/pages/[[...slug]].js:26:78
    at __webpack_require__.a (/var/task/.next/server/webpack-runtime.js:89:13)
    at 4647 (/var/task/.next/server/pages/[[...slug]].js:11:21)
    at __webpack_require__ (/var/task/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/var/task/.next/server/pages/[[...slug]].js:2425:39)
    at /var/task/.next/server/pages/[[...slug]].js:2426:69
    at __webpack_require__.X (/var/task/.next/server/webpack-runtime.js:177:21)
`

## Additional context

I have made changes to your code so it is not 100% similar and additionally, the problem can come from the yarn install & yarn build:open-next command, but if you ever encountered any problem regarding an expected accessToken it would be a great help if you can give me a hint.

WIth kind regards

**Comment by ThomasTusche** [comment]
Seems the lambda was expecting a Contentful Token in its environment variables. Sorry for bothering :)
